name: sunny
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.7
  nyxx: ^6.8.1
  serinus: ^2.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
